name: Improvement
description: Create an issue for an improvement to an existing feature.
title: "[IMPROVEMENT]: "
labels: ["improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this improvement request !
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the improvement you would like to be implemented.
      placeholder: "Describe the improvement you would like to be implemented."
    validations:
      required: true
  - type: textarea
    attributes:
      label: What has to be done
      description: Describe the steps to implement the improvement.
      placeholder: "Describe the steps to implement the improvement."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Describe the priority of the improvement.
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Project parts
      description: Select the parts of the project that are affected by the improvement.
      options:
        - label: Connexion / Subscription screen
        - label: Discover new places
        - label: Take a video
        - label: Access to videos
        - label: Settings screen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the improvement request here.
      placeholder: "Add any other context or screenshots about the improvement request here."
    validations:
      required: false
