name: Create a tag

on:
  # Trigger manually from github
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        type: string
      version:
        description: 'Tag version'
        required: true
        type: string
        default: '0.0.0'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ github.event.inputs.version }}
          tag_exists_error: false
          message: ${{ github.event.inputs.tag_name }}

      # Print result using the env variable.
      -  run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"

      # Print result using the action output.
      - run: |
          echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"
