name: Generate documentation

on:
  push:
    branches:
      - main

jobs:
  generate_documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set variables
        run: |
          cat >> "$GITHUB_ENV" <<EOF
          NODE_VERSION=$(cat _node-version)
          EOF

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate documentation
        run: yarn run documentation

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/documentation
