name: Linter

on:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run Eslint
        run: yarn run lint

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{tsx,ts,jsx,js} --config ${{ github.workspace }}/.prettierrc.js
