name: Push Action

on:
  push:
    branches-ignore:
      - main

jobs:
  linting:
    uses: NoLoSay/NoLoApp/.github/workflows/front_end_linting.yml@NOLO-169-Connect-all-setup-branches

  testing:
    needs: linting
    uses: NoLoSay/NoLoApp/.github/workflows/run_tests.yml@NOLO-169-Connect-all-setup-branches

  documentation:
    needs: [linting, testing]
    uses: NoLoSay/NoLoApp/.github/workflows/generate_documentation.yml@NOLO-169-Connect-all-setup-branches
