name: Push Action

on:
  push:
    branches:
      - main

jobs:
  linting:
    uses: NoLoSay/NoLoApp/.github/workflows/front_end_linting.yml@main

  testing:
    needs: linting
    uses: NoLoSay/NoLoApp/.github/workflows/run_tests.yml@main

  documentation:
    needs: [linting, testing]
    uses: NoLoSay/NoLoApp/.github/workflows/generate_documentation.yml@main
