name: Compress Assets

on:
  workflow_call:

jobs:
  compress-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install github cli
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Compress images
        run: |
          sudo apt-get install -y optipng

          find ./assets -name '*.png' -exec optipng -o7 {} \;

          git diff --exit-code
          if [ $? -eq 0 ]; then
            echo "No changes detected."
          else
            echo "Images not compressed. Run `find ./assets -name '*.png' -exec optipng -o7 {} \;` to fix it."
            exit 1
          fi
