name: Compress Assets

on:
  workflow_call:

jobs:
  compress-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compress images
        run: |
          sudo apt-get install -y optipng

          find ./assets -name '*.png' -exec optipng -o7 {} \;

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ./assets
          git diff --cached --exit-code || git commit -m "Compress PNG assets" --allow-empty
          git push
