name: Pull request

on:
  pull_request:

jobs:
  linting:
    uses: NoLoSay/NoLoApp/.github/workflows/front_end_linting.yml@main

  testing:
    needs: linting
    uses: NoLoSay/NoLoApp/.github/workflows/run_tests.yml@main
    secrets: inherit
