name: Push Action

on: push

jobs:
  linting:
    uses: NoLoSay/NoLoApp/.github/workflows/front_end_linting.yml@NOLO-169-Connect-all-setup-branches

  testing:
    needs: linting
    uses: NoLoSay/NoLoApp/.github/workflows/run_tests.yml@NOLO-169-Connect-all-setup-branches
