name: Push Action

on:
  push:
    branches-ignore:
      - main

jobs:
  linting:
    uses: NoLoSay/NoLoApp/.github/workflows/front_end_linting.yml@main

  optimization:
    uses: NoLoSay/NoLoApp/.github/workflows/optimize_images.yml@main

  testing:
    needs: [linting, optimization]
    uses: NoLoSay/NoLoApp/.github/workflows/run_tests.yml@main
    secrets: inherit
